= Emerald API Client for Javascript

image:https://github.com/emeraldpay/emerald-api-js/workflows/Unit%20Tests/badge.svg["Unit Tests"]
image:https://img.shields.io/github/license/emeraldpay/emerald-api-js.svg?maxAge=2592000["License",link="https://github.com/emeraldpay/emerald-api-js/blob/master/LICENSE"]
image:https://img.shields.io/gitter/room/emeraldpay/community.svg["Gitter",link="https://gitter.im/emeraldpay/community"]

== NodeJS / Electron Client

image:https://img.shields.io/npm/v/@emeraldpay/api-node.svg["npm (scoped)",link="https://www.npmjs.com/package/@emeraldpay/api-node"]

== Web Client

image:https://img.shields.io/npm/v/@emeraldpay/api-web.svg["npm (scoped)",link="https://www.npmjs.com/package/@emeraldpay/api-web"]

== Development

=== Build Instructions

.Prepare Environment
----
yarn install
----

.Build all
----
yarn workspaces run build
----

.Build individual modules
----
yarn workspace @emeraldpay/api run build
yarn workspace @emeraldpay/api-node run build
yarn workspace @emeraldpay/api-web run build
----

.Compile individual modules
----
yarn workspace @emeraldpay/api run build:ts
yarn workspace @emeraldpay/api-node run build:ts
yarn workspace @emeraldpay/api-web run build:ts
----

.Test individual modules
----
yarn workspace @emeraldpay/api run test
yarn workspace @emeraldpay/api-node run test
yarn workspace @emeraldpay/api-web run test
----

=== Update Protobuf

This Client references Emerald API protobuf through Git Submodules.
Original Protobuf definitions are located at: https://github.com/emeraldpay/emerald-grpc

.Update Protobuf definitions to the latest:
----
git submodule update --remote
git commit api-definitions
----

== License

Copyright 2020 EmeraldPay, Inc

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.