name: Publish package

on:
  release:
    types: [ created ]

jobs:
  npm:
    name: Publish to NPM ${{ matrix.package }}
    strategy:
      matrix:
        # it's a DIRECTORY insides the ./src/
        package: [ "core", "node", "web" ]
    runs-on: ubuntu-latest
    # CONTINUE because it can fail for completely irrelevant reason like IO timeout and that would prevent the
    # whole job from restarting because some part of the packages are already published and would fail anyway
    continue-on-error: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          always-auth: true

      - name: Configure NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install JS dependencies
        run: yarn install

      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Build
        run: yarn workspaces foreach run build

      - name: Publish to NPM
        run: npm publish --access=public
        working-directory: packages/${{ matrix.package }}
